#!/bin/bash


cdrom=`file /dev/cdrom | awk '{print $5}' | cut -c2-9`
dvd=`file /dev/dvd | awk '{print $5}' | cut -c2-9`
	
#we add the installationmedia here
if [ -b /dev/cdrom ] ; then
	mkdir -p /mnt/cdrom
	mount /dev/cdrom /mnt/cdrom >/dev/null 2>&1
	[ -z "`grep '\/mnt/cdrom' /etc/fstab`" ] && echo "" >> /etc/fstab && \
	echo "/dev/$cdrom      /mnt/cdrom      auto    auto,users              0       0" >> /etc/fstab 
fi

if [ "$cdrom" != "$dvd" ] ; then
	mkdir -p /mnt/dvdrom
	mount /dev/$dvd /mnt/dvdrom >/dev/null 2>&1
	[ -z "`grep '\/mnt/dvdrom' /etc/fstab`" ] && echo "" >> /etc/fstab && \
	echo "/dev/$dvd      /mnt/dvdrom      auto    auto,users              0       0" >> /etc/fstab 
fi

